#!/usr/bin/env python3

#### SHUTDOWN SYSTEM LEDS
from gpiozero import Button, LEDBoard
from signal import pause
import warnings, os, sys

# Get this GPIO from kiln-controller config.py file.
heat_ledGPIO = 17
heat_led=LEDBoard(heat_ledGPIO)
heat_led.off

# This is specific to Mark's adapter board.
service_running_ledGPIO = 27
service_running_led=LEDBoard(service_running_ledGPIO)
service_running_led.off

# This is specific to Mark's adapter board.
#service_aux_ledGPIO = 22
#service_aux_led=LEDBoard(service_aux_ledGPIO)
#service_aux_led.blink(on_time=1, off_time=1)
#service_aux_led.on 


#### END - CONROL SYSTEM LEDS

#### Start service
os.system("sudo systemctl stop kiln-controller.service")
#### Echo process to user
os.system ("sleep 2")
os.system("ps aux | grep 'kiln-controller' | awk '{print $2"   "$12}'")

